[pytest]
filterwarnings =
    ignore:Setting the shape on a NumPy array has been deprecated:DeprecationWarning:joblib.*
    ignore:The `__get_pydantic_core_schema__` method of the `BaseModel` class is deprecated:DeprecationWarning
    ignore:Please use `import python_multipart` instead:PendingDeprecationWarning
